# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shawn', '0003_auto_20170131_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetail',
            old_name='ID',
            new_name='BlogID',
        ),
    ]
