# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shawn', '0005_auto_20170131_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetail',
            old_name='Blog',
            new_name='blog',
        ),
    ]
