# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shawn', '0006_auto_20170131_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='blogdetail',
            name='content',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
