# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shawn', '0008_auto_20170201_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetail',
            name='title',
            field=models.TextField(default='HelloWorld'),
        ),
    ]
